### ISSUE TITLE
numba版本

### ISSUE THREAD

**Issue by wxywxywxy11** [yimutianyang/KDD24-GBSR#3]
你好，我在运行使总出现numba报错问题 Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
   expecting {i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]} but got {i8*, i8*, i64, i64, i32*, [1 x i64], [1 x i64]}
，请问numba的版本是多少？

**Comment by yimutianyang** [comment]
你好，
使用的numba==0.56.2
根据上述报错原因，应该是numba封装的数据格式中有一项要求是int64，但是代码中输入的是int32类型的数据，可以再检查下。

**Comment by wxywxywxy11** [comment]
好的，已经可以运行了，非常感谢！

**Comment by yimutianyang** [comment]
不客气！
